import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

from config import (
    X_CSV_FILE, Y_CSV_FILE, COLS_TO_ENCODE, MIN_CLASS_COUNT, 
    TEST_SIZE, RANDOM_STATE, DT_MAX_DEPTH, DT_MIN_SAMPLES_SPLIT,
    DT_IMPORTANCE_PNG
)

def generate_dt_importance():

    try:
        X = pd.read_csv(X_CSV_FILE)
        y = pd.read_csv(Y_CSV_FILE)
    except FileNotFoundError:
        print("Error")
        return

    cols_to_encode = [col for col in COLS_TO_ENCODE if col in X.columns]
    print("Applying one-hot encoding...")
    X_encoded = pd.get_dummies(X, columns=cols_to_encode)

    if isinstance(y, pd.DataFrame):
        y = y.iloc[:, 0]
    
    # AI generated by genimi for model part
    counts = y.value_counts()
    valid_classes = counts[counts > MIN_CLASS_COUNT].index
    valid_mask = y.isin(valid_classes)
    X_encoded = X_encoded[valid_mask]
    y = y[valid_mask]

    le = LabelEncoder()
    y_encoded = le.fit_transform(y)

    X_train, X_test, y_train, y_test = train_test_split(
        X_encoded, y_encoded, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y_encoded
    )

    dt_model = DecisionTreeClassifier(max_depth=DT_MAX_DEPTH, min_samples_split=DT_MIN_SAMPLES_SPLIT, random_state=RANDOM_STATE)
    dt_model.fit(X_train, y_train)
    importances = dt_model.feature_importances_
    features = X_train.columns

    importance_df = pd.DataFrame({
        'Feature': features,
        'Importance': importances
    })

    top_10 = importance_df.sort_values(by='Importance', ascending=False).head(10)
    
    print(top_10.to_string(index=False))

    plt.figure(figsize=(10, 6))
    
    plt.barh(top_10['Feature'][::-1], top_10['Importance'][::-1], color='coral', edgecolor='black')
    
    plt.xlabel('Decision Tree Feature Importance Score', fontsize=12)
    plt.ylabel('Feature Name', fontsize=12)
    plt.title('Top 10 Most Important Features (Decision Tree)', fontsize=14, fontweight='bold')
    
    plt.grid(axis='x', linestyle='--', alpha=0.7)
    plt.tight_layout()
    
    output_png = DT_IMPORTANCE_PNG
    plt.savefig(output_png, dpi=300)

if __name__ == "__main__":
    generate_dt_importance()
