import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

def generate_dt_importance():

    try:
        X = pd.read_csv('x.csv')
        y = pd.read_csv('y.csv')
    except FileNotFoundError:
        print("Error")
        return

    cols_to_encode = [
        'WHYTO', 'WHYFROM', 'URBRUR', 'URBAN', 'HBHUR', 'CENSUS_R', 
        'R_SEX', 'EDUC', 'WORKER', 'LIF_CYC', 'MEDCOND', 'CONDRIVE', 
        'W_CHAIR', 'W_NONE', 'DRIVER', 'TRPHHVEH', 'TDWKND', 'LOOP_TRIP'
    ]

    cols_to_encode = [col for col in cols_to_encode if col in X.columns]
    print("Applying one-hot encoding...")
    X_encoded = pd.get_dummies(X, columns=cols_to_encode)

    if isinstance(y, pd.DataFrame):
        y = y.iloc[:, 0]
    
    # AI generated by genimi for model part
    counts = y.value_counts()
    valid_classes = counts[counts > 10].index
    valid_mask = y.isin(valid_classes)
    X_encoded = X_encoded[valid_mask]
    y = y[valid_mask]

    le = LabelEncoder()
    y_encoded = le.fit_transform(y)

    X_train, X_test, y_train, y_test = train_test_split(
        X_encoded, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
    )

    dt_model = DecisionTreeClassifier(max_depth=20, min_samples_split=50, random_state=42)
    dt_model.fit(X_train, y_train)
    importances = dt_model.feature_importances_
    features = X_train.columns

    importance_df = pd.DataFrame({
        'Feature': features,
        'Importance': importances
    })

    top_10 = importance_df.sort_values(by='Importance', ascending=False).head(10)
    
    print(top_10.to_string(index=False))

    plt.figure(figsize=(10, 6))
    
    plt.barh(top_10['Feature'][::-1], top_10['Importance'][::-1], color='coral', edgecolor='black')
    
    plt.xlabel('Decision Tree Feature Importance Score', fontsize=12)
    plt.ylabel('Feature Name', fontsize=12)
    plt.title('Top 10 Most Important Features (Decision Tree)', fontsize=14, fontweight='bold')
    
    plt.grid(axis='x', linestyle='--', alpha=0.7)
    plt.tight_layout()
    
    output_png = 'top_10_features_dt.png'
    plt.savefig(output_png, dpi=300)

if __name__ == "__main__":
    generate_dt_importance()
